title: Reversecoding
email: mario@reversecoding.net
description: >-
  Traditionally teaching methods start with the theory and then move the examples. I prefer do the opposite,
  I find it more effective. I like start from a real example, play with that, break it down, ask my self some
  questions and then move to the theory.  Reversecoding.net follows this approach: hope you'll find it helpful.
  Thanks for visiting us!
baseurl: ""
url: "https://reversecoding.net/"
twitter_username: mariopiogioiosa
github_username:  mariopiogioiosa
linkedin_username: mariopiogioiosa

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

google_analytics: UA-138490178-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
