title: Reverse Coding
email: mario@reversecoding.net
description: >-
  Traditionally teaching methods start with first with theory and then move to practice. I prefer do the opposite,
  I find it more effective. I prefer to start from a real example, to play with that, to break it down, to ask my
  self some questions and only then to move to the theory.  Reversecoding.net follows this approach: hope you'll find
  it helpful. Thanks for visiting us!
baseurl: ""
url: "https://reversecoding.net"
twitter_username: mariopiogioiosa
github_username:  mariopiogioiosa
linkedin_username: mariopiogioiosa

disqus:
  shortname: reversecoding

markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

google_analytics: UA-138490178-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
